### ISSUE TITLE
Initial Report

### ISSUE THREAD

**Issue by rahlk** [rahlk/Experimental-Algorithms#1]
### To add:
- [x] Brief description of your team: name(s) and short list of skills
- [ ] A description of the problem (without referring to solution methods)
- [x] Algorithm(s) you wish to investigate (give an overview with pointers to the literature)
- [x] Machine architectures (if important)
- [x] What you hope to find out
- [x] The sequence of steps you intend to take: roughly -- I won't hold you to this, but it'll give me an opportunity to suggest approaches
- [x] Citations to papers, either ones you've already looked at or intend to look at

**Comment by rahlk** [comment]
@bigfatnoob Working on this.

**Comment by bigfatnoob** [comment]
Is there a sharelatex url? I could add some stuff too

**Comment by rahlk** [comment]
May I have your Sharelatex email id?

**Comment by bigfatnoob** [comment]
george.meg91@gmail.com

**Comment by rahlk** [comment]
This book may be useful: http://catalog.lib.ncsu.edu/record/NCSU2380465

**Comment by rahlk** [comment]
Chapter 13 specifically
